services:
  # Backend Spring Boot
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis
    networks:
      - habittracker-network

  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    networks:
      - habittracker-network
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api

  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: habittracker_db
      POSTGRES_USER: habittracker_user
      POSTGRES_PASSWORD: habittracker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habittracker-network

  # Cache Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - habittracker-network

  # Interface d'administration BDD
  adminer:
    image: adminer:4.8.1
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - habittracker-network

volumes:
  postgres_data:

networks:
  habittracker-network:
    driver: bridge