services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: habittracker_db
      POSTGRES_USER: habittracker_user
      POSTGRES_PASSWORD: habittracker_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  adminer:
    image: adminer:4.8.1
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: